export const timelineElements = [
    {
        key: 1,
        title: "Bachelor of Human Life and Environment",
        place: "Nara Women's University (Nara, Japan)",
        date: "2012 - 2016",
        icon: 'school',
        description: "My education provided a comprehensive understanding of various facets of architecture, including design, history, and structural analysis. Through a blend of theoretical coursework and practical projects, I developed a strong foundation in architectural principles and practices.",
    },
    {
        key: 2,
        title: "Architectural Engineer",
        place: "Nagano Prefecture (Nagano, Japan)",
        date: "2016 - 2022",
        icon: 'work',
        description: "In this role, I was responsible for overseeing the construction of new facilities and maintaining existing structures. This position allowed me to cultivate essential skills in problem-solving, project management, and creativity.",
    },
    {
        key: 3,
        title: "",
        place: "",
        date: "",
        icon: 'school',
        description: "",
    },
    {
        key: 4,
        title: "",
        place: "",
        date: "",
        icon: 'school',
        description: "",
    },
    {
        key: 5,
        title: "",
        place: "",
        date: "",
        icon: 'school',
        description: "",
    },
    {
        key: 6,
        title: "",
        place: "",
        date: "",
        icon: 'school',
        description: "",
    },
]